---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zima-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zima
  labels:
    name: zima
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zima
  template:
    metadata:
      labels:
        app: zima
    spec:
      containers:
      - name: zima
        image: dockurr/zima
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8006
            name: vnc
            protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /storage
          name: storage
        - mountPath: /dev/kvm
          name: dev-kvm
        - mountPath: /dev/net/tun
          name: dev-tun
      terminationGracePeriodSeconds: 120
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: zima-pvc
      - hostPath:
          path: /dev/kvm
          type: CharDevice
        name: dev-kvm
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-tun
---
apiVersion: v1
kind: Service
metadata:
  name: zima
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
    - name: vnc
      port: 8006
      protocol: TCP
      targetPort: 8006
  selector:
    app: zima
  type: ClusterIP
