services:
  zima:
    container_name: zima
    image: ghcr.io/dockur/zima
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:80
      - 8006:8006
    volumes:
      - ./zima:/storage
    restart: on-failure
    stop_grace_period: 1m
